import { style } from "@macaron-css/core";
import { For } from "solid-js";
import { SiteWordmark } from "~/components/SiteWordmark";
import { RADIX_ICONS, RadixIcon } from "~/constants/radixIcons";

export default function Page() {
  return (
    <div>
      <SiteWordmark title="solid radix icons" />
      <div class="flex justify-center space-x-16">
        <For each={ICON_MAP}>
          {(column) => (
            <div>
              <For each={column}>
                {(category) => (
                  <div>
                    <h2
                      class={style({
                        fontSize: 12,
                        // fontFamily: "Verdana",
                        lineHeight: `${15 + 36 * 2}px`,
                      })}
                    >
                      {category.name}
                    </h2>
                    <div
                      class={style({
                        display: "grid",
                        gridTemplateColumns: "repeat(6, 15px)",
                        gap: 36,
                      })}
                    >
                      <For each={category.icons}>
                        {(icon) => RADIX_ICONS[icon]?.[0]}
                      </For>
                    </div>
                  </div>
                )}
              </For>
            </div>
          )}
        </For>
      </div>
    </div>
  );
}

type Category = { name: string; icons: RadixIcon[] };

type Column = Category[];

type IconMap = Column[];

const ICON_MAP: IconMap = [
  [
    {
      name: "Typography",
      icons: [
        "FontStyle",
        "FontItalic",
        "FontRoman",
        "FontBold",
        "LetterCaseUppercase",
        "LetterCaseCapitalize",
        "LetterCaseLowercase",
        "LetterCaseToggle",
        "LetterSpacing",
        "AlignBaseline",
        "FontSize",
        "FontFamily",
        "Heading",
        "Text",
        "TextNone",
        "LineHeight",
        "Underline",
        "Strikethrough",
        "Overline",
        "Pilcrow",
        "TextAlignLeft",
        "TextAlignCenter",
        "TextAlignRight",
        "TextAlignRight",
        "TextAlignJustify",
        "TextAlignTop",
        "TextAlignMiddle",
        "TextAlignBottom",
        "Dash",
      ],
    },
    {
      name: "Music",
      icons: [
        "Play",
        "Resume",
        "Pause",
        "Stop",
        "TrackPrevious",
        "TrackNext",
        "Loop",
        "Shuffle",
        "SpeakerLoud",
        "SpeakerModerate",
        "SpeakerQuiet",
        "SpeakerOff",
      ],
    },
    {
      name: "Abstract",
      icons: [
        "HamburgerMenu",
        "Cross1",
        "DotsHorizontal",
        "DotsVertical",
        "Plus",
        "Minus",
        "Check",
        "Cross2",
        "CheckCircled",
        "CrossCircled",
        "PlusCircled",
        "MinusCircled",
        "QuestionMark",
        "QuestionMarkCircled",
        "InfoCircled",
        "Accessibility",
        "ExclamationTriangle",
        "Share1",
        "Share2",
        "ExternalLink",
        "OpenInNewWindow",
        "Enter",
        "Exit",
        "Download",
        "Upload",
        "Reset",
        "Reload",
        "Update",
        "EnterFullScreen",
        "ExitFullScreen",
        "DragHandleVertical",
        "DragHandleHorizontal",
        "DragHandleDots1",
        "DragHandleDots2",
        "Dot",
        "DotFilled",
        "Commit",
        "Slash",
        "Circle",
        "CircleBackslash",
        "Half1",
        "Half2",
        "ViewVertical",
        "ViewHorizontal",
        "ViewGrid",
        "ViewNone",
        "Square",
        "Copy",
      ],
    },
    {
      name: "Logos",
      icons: [
        "ModulzLogo",
        "StitchesLogo",
        "FigmaLogo",
        "FramerLogo",
        "SketchLogo",
        "TwitterLogo",
        "IconJarLogo",
        "GitHubLogo",
        "VercelLogo",
        "CodeSandboxLogo",
        "NotionLogo",
        "DiscordLogo",
        "InstagramLogo",
        "LinkedInLogo",
      ],
    },
  ],
  [
    {
      name: "Arrows",
      icons: [
        "ArrowLeft",
        "ArrowRight",
        "ArrowUp",
        "ArrowDown",
        "ArrowTopLeft",
        "ArrowTopRight",
        "ArrowBottomLeft",
        "ArrowBottomRight",
        "ChevronLeft",
        "ChevronRight",
        "ChevronUp",
        "ChevronDown",
        "DoubleArrowLeft",
        "DoubleArrowRight",
        "DoubleArrowUp",
        "DoubleArrowDown",
        "ThickArrowLeft",
        "ThickArrowRight",
        "ThickArrowUp",
        "ThickArrowDown",
        "TriangleLeft",
        "TriangleRight",
        "TriangleUp",
        "TriangleDown",
        "CaretLeft",
        "CaretRight",
        "CaretUp",
        "CaretDown",
        "CaretSort",
        "Width",
        "Height",
        "Size",
        "Move",
        "AllSides",
      ],
    },
    {
      name: "Objects",
      icons: [
        "MagnifyingGlass",
        "Gear",
        "Bell",
        "Home",
        "LockClosed",
        "LockOpen1",
        "LockOpen2",
        "Backpack",
        "Camera",
        "PaperPlane",
        "Rocket",
        "EnvelopeClosed",
        "EnvelopeOpen",
        "ChatBubble",
        "Link1",
        "LinkNone1",
        "LinkBreak1",
        "Link2",
        "LinkNone2",
        "LinkBreak2",
        "Trash",
        "Pencil1",
        "Pencil2",
        "Bookmark",
        "BookmarkFilled",
        "DrawingPin",
        "DrawingPinFilled",
        "SewingPin",
        "SewingPinFilled",
        "Cube",
        "Archive",
        "CrumpledPaper",
        "Mix",
        "MixerHorizontal",
        "MixerVertical",
        "File",
        "FileText",
        "FilePlus",
        "FileMinus",
        "Reader",
        "CardStack",
        "CardStackPlus",
        "CardStackMinus",
        "IdCard",
        "Crosshair1",
        "Crosshair2",
        "Target",
        "Disc",
        "Globe",
        "Sun",
        "Moon",
        "Clock",
        "Timer",
        "CounterClockwiseClock",
        "CountdownTimer",
        "Stopwatch",
        "LapTimer",
        "LightningBolt",
        "MagicWand",
        "Face",
        "Person",
        "EyeOpen",
        "EyeNone",
        "EyeClosed",
        "Hand",
        "RulerHorizontal",
        "RulerSquare",
        "Clipboard",
        "ClipboardCopy",
        "Desktop",
        "Laptop",
        "Mobile",
        "Keyboard",
        "Star",
        "StarFilled",
        "Heart",
        "HeartFilled",
        "Scissors",
        "HobbyKnife",
        "Eraser",
        "Cookie",
      ],
    },
  ],
  [
    {
      name: "Design",
      icons: [
        "Frame",
        "Crop",
        "Layers",
        "Stack",
        "Tokens",
        "Component1",
        "Component2",
        "Symbol",
        "ComponentInstance",
        "ComponentNone",
        "ComponentBoolean",
        "ComponentPlaceholder",
        "Opacity",
        "BlendingMode",
        "MaskOn",
        "MaskOff",
        "ColorWheel",
        "Shadow",
        "ShadowNone",
        "ShadowNone",
        "ShadowInner",
        "ShadowOuter",
        "Value",
        "ValueNone",
        "ZoomIn",
        "ZoomOut",
        "TransparencyGrid",
        "Group",
        "Dimensions",
        "RotateCounterClockwise",
        "Columns",
        "Rows",
        "Transform",
        "BoxModel",
        "Padding",
        "Margin",
        "Angle",
        "CursorArrow",
        "CursorText",
        "ColumnSpacing",
        "RowSpacing",
      ],
    },
    {
      name: "Components",
      icons: [
        "Box",
        "AspectRatio",
        "Container",
        "Section",
        "Layout",
        "Grid",
        "Table",
        "Image",
        "Switch",
        "Checkbox",
        "Radiobutton",
        "Avatar",
        "Button",
        "Badge",
        "Input",
        "Slider",
        "Quote",
        "Code",
        "ListBullet",
        "DropdownMenu",
        "Video",
        "PieChart",
        "Calendar",
        "Dashboard",
        "ActivityLog",
        "BarChart",
        "DividerVertical",
        "DividerHorizontal",
      ],
    },
    {
      name: "Borders and corners",
      icons: [
        "BorderAll",
        "BorderSplit",
        "BorderNone",
        "BorderLeft",
        "BorderRight",
        "BorderTop",
        "BorderBottom",
        "Corners",
        "CornerTopLeft",
        "CornerTopRight",
        "CornerBottomLeft",
        "CornerBottomRight",
        "BorderStyle",
        "BorderSolid",
        "BorderDashed",
        "BorderDotted",
      ],
    },
    {
      name: "Alignment",
      icons: [
        "AlignTop",
        "AlignCenterVertically",
        "AlignBottom",
        "StretchVertically",
        "AlignLeft",
        "AlignCenterHorizontally",
        "AlignRight",
        "StretchHorizontally",
        "SpaceBetweenHorizontally",
        "SpaceEvenlyHorizontally",
        "SpaceBetweenVertically",
        "SpaceEvenlyVertically",
        "PinLeft",
        "PinRight",
        "PinTop",
        "PinBottom",
      ],
    },
  ],
];
