import {
  AccessibilityIcon,
  ActivityLogIcon,
  AlignBaselineIcon,
  AlignBottomIcon,
  AlignCenterHorizontallyIcon,
  AlignCenterVerticallyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AllSidesIcon,
  AngleIcon,
  ArchiveIcon,
  ArrowBottomLeftIcon,
  ArrowBottomRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTopLeftIcon,
  ArrowTopRightIcon,
  ArrowUpIcon,
  AspectRatioIcon,
  AvatarIcon,
  BackpackIcon,
  BadgeIcon,
  BarChartIcon,
  BellIcon,
  BlendingModeIcon,
  BookmarkFilledIcon,
  BookmarkIcon,
  BorderAllIcon,
  BorderBottomIcon,
  BorderDashedIcon,
  BorderDottedIcon,
  BorderLeftIcon,
  BorderNoneIcon,
  BorderRightIcon,
  BorderSolidIcon,
  BorderSplitIcon,
  BorderStyleIcon,
  BorderTopIcon,
  BorderWidthIcon,
  BoxIcon,
  BoxModelIcon,
  ButtonIcon,
  CalendarIcon,
  CameraIcon,
  CardStackIcon,
  CardStackMinusIcon,
  CardStackPlusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretSortIcon,
  CaretUpIcon,
  ChatBubbleIcon,
  CheckCircledIcon,
  CheckIcon,
  CheckboxIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleBackslashIcon,
  CircleIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  ClockIcon,
  CodeIcon,
  CodeSandboxLogoIcon,
  ColorWheelIcon,
  ColumnSpacingIcon,
  ColumnsIcon,
  CommitIcon,
  Component1Icon,
  Component2Icon,
  ComponentBooleanIcon,
  ComponentInstanceIcon,
  ComponentNoneIcon,
  ComponentPlaceholderIcon,
  ContainerIcon,
  CookieIcon,
  CopyIcon,
  CornerBottomLeftIcon,
  CornerBottomRightIcon,
  CornerTopLeftIcon,
  CornerTopRightIcon,
  CornersIcon,
  CountdownTimerIcon,
  CounterClockwiseClockIcon,
  CropIcon,
  Cross1Icon,
  Cross2Icon,
  CrossCircledIcon,
  Crosshair1Icon,
  Crosshair2Icon,
  CrumpledPaperIcon,
  CubeIcon,
  CursorArrowIcon,
  CursorTextIcon,
  DashIcon,
  DashboardIcon,
  DesktopIcon,
  DimensionsIcon,
  DiscIcon,
  DiscordLogoIcon,
  DividerHorizontalIcon,
  DividerVerticalIcon,
  DotFilledIcon,
  DotIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DoubleArrowDownIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  DoubleArrowUpIcon,
  DownloadIcon,
  DragHandleDots1Icon,
  DragHandleDots2Icon,
  DragHandleHorizontalIcon,
  DragHandleVerticalIcon,
  DrawingPinFilledIcon,
  DrawingPinIcon,
  DropdownMenuIcon,
  EnterFullScreenIcon,
  EnterIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  EraserIcon,
  ExclamationTriangleIcon,
  ExitFullScreenIcon,
  ExitIcon,
  ExternalLinkIcon,
  EyeClosedIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  FaceIcon,
  FigmaLogoIcon,
  FileIcon,
  FileMinusIcon,
  FilePlusIcon,
  FileTextIcon,
  FontBoldIcon,
  FontFamilyIcon,
  FontItalicIcon,
  FontRomanIcon,
  FontSizeIcon,
  FontStyleIcon,
  FrameIcon,
  FramerLogoIcon,
  GearIcon,
  GitHubLogoIcon,
  GlobeIcon,
  GridIcon,
  GroupIcon,
  Half1Icon,
  Half2Icon,
  HamburgerMenuIcon,
  HandIcon,
  HeadingIcon,
  HeartFilledIcon,
  HeartIcon,
  HeightIcon,
  HobbyKnifeIcon,
  HomeIcon,
  IconJarLogoIcon,
  IdCardIcon,
  ImageIcon,
  InfoCircledIcon,
  InputIcon,
  InstagramLogoIcon,
  KeyboardIcon,
  LapTimerIcon,
  LaptopIcon,
  LayersIcon,
  LayoutIcon,
  LetterCaseCapitalizeIcon,
  LetterCaseLowercaseIcon,
  LetterCaseToggleIcon,
  LetterCaseUppercaseIcon,
  LetterSpacingIcon,
  LightningBoltIcon,
  LineHeightIcon,
  Link1Icon,
  Link2Icon,
  LinkBreak1Icon,
  LinkBreak2Icon,
  LinkNone1Icon,
  LinkNone2Icon,
  LinkedInLogoIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LockOpen2Icon,
  LoopIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MarginIcon,
  MaskOffIcon,
  MaskOnIcon,
  MinusCircledIcon,
  MinusIcon,
  MixIcon,
  MixerHorizontalIcon,
  MixerVerticalIcon,
  MobileIcon,
  ModulzLogoIcon,
  MoonIcon,
  MoveIcon,
  NotionLogoIcon,
  OpacityIcon,
  OpenInNewWindowIcon,
  OverlineIcon,
  PaddingIcon,
  PaperPlaneIcon,
  PauseIcon,
  Pencil1Icon,
  Pencil2Icon,
  PersonIcon,
  PieChartIcon,
  PilcrowIcon,
  PinBottomIcon,
  PinLeftIcon,
  PinRightIcon,
  PinTopIcon,
  PlayIcon,
  PlusCircledIcon,
  PlusIcon,
  QuestionMarkCircledIcon,
  QuestionMarkIcon,
  QuoteIcon,
  RadiobuttonIcon,
  ReaderIcon,
  ReloadIcon,
  ResetIcon,
  ResumeIcon,
  RocketIcon,
  RotateCounterClockwiseIcon,
  RowSpacingIcon,
  RowsIcon,
  RulerHorizontalIcon,
  RulerSquareIcon,
  ScissorsIcon,
  SectionIcon,
  SewingPinFilledIcon,
  SewingPinIcon,
  ShadowIcon,
  ShadowInnerIcon,
  ShadowNoneIcon,
  ShadowOuterIcon,
  Share1Icon,
  Share2Icon,
  ShuffleIcon,
  SizeIcon,
  SketchLogoIcon,
  SlashIcon,
  SliderIcon,
  SpaceBetweenHorizontallyIcon,
  SpaceBetweenVerticallyIcon,
  SpaceEvenlyHorizontallyIcon,
  SpaceEvenlyVerticallyIcon,
  SpeakerLoudIcon,
  SpeakerModerateIcon,
  SpeakerOffIcon,
  SpeakerQuietIcon,
  SquareIcon,
  StackIcon,
  StarFilledIcon,
  StarIcon,
  StitchesLogoIcon,
  StopIcon,
  StopwatchIcon,
  StretchHorizontallyIcon,
  StretchVerticallyIcon,
  StrikethroughIcon,
  SunIcon,
  SwitchIcon,
  SymbolIcon,
  TableIcon,
  TargetIcon,
  TextAlignBottomIcon,
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignMiddleIcon,
  TextAlignRightIcon,
  TextAlignTopIcon,
  TextIcon,
  TextNoneIcon,
  ThickArrowDownIcon,
  ThickArrowLeftIcon,
  ThickArrowRightIcon,
  ThickArrowUpIcon,
  TimerIcon,
  TokensIcon,
  TrackNextIcon,
  TrackPreviousIcon,
  TransformIcon,
  TransparencyGridIcon,
  TrashIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  TwitterLogoIcon,
  UnderlineIcon,
  UpdateIcon,
  UploadIcon,
  ValueIcon,
  ValueNoneIcon,
  VercelLogoIcon,
  VideoIcon,
  ViewGridIcon,
  ViewHorizontalIcon,
  ViewNoneIcon,
  ViewVerticalIcon,
  WidthIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "solid-radix-icons";

export const RADIX_ICONS = {
  Accessibility: [<AccessibilityIcon />, "Accessibility"],
  ActivityLog: [<ActivityLogIcon />, "ActivityLog"],
  AlignBaseline: [<AlignBaselineIcon />, "AlignBaseline"],
  AlignBottom: [<AlignBottomIcon />, "AlignBottom"],
  AlignCenterHorizontally: [
    <AlignCenterHorizontallyIcon />,
    "AlignCenterHorizontally",
  ],
  AlignCenterVertically: [
    <AlignCenterVerticallyIcon />,
    "AlignCenterVertically",
  ],
  AlignLeft: [<AlignLeftIcon />, "AlignLeft"],
  AlignRight: [<AlignRightIcon />, "AlignRight"],
  AlignTop: [<AlignTopIcon />, "AlignTop"],
  AllSides: [<AllSidesIcon />, "AllSides"],
  Angle: [<AngleIcon />, "Angle"],
  Archive: [<ArchiveIcon />, "Archive"],
  ArrowBottomLeft: [<ArrowBottomLeftIcon />, "ArrowBottomLeft"],
  ArrowBottomRight: [<ArrowBottomRightIcon />, "ArrowBottomRight"],
  ArrowDown: [<ArrowDownIcon />, "ArrowDown"],
  ArrowLeft: [<ArrowLeftIcon />, "ArrowLeft"],
  ArrowRight: [<ArrowRightIcon />, "ArrowRight"],
  ArrowTopLeft: [<ArrowTopLeftIcon />, "ArrowTopLeft"],
  ArrowTopRight: [<ArrowTopRightIcon />, "ArrowTopRight"],
  ArrowUp: [<ArrowUpIcon />, "ArrowUp"],
  AspectRatio: [<AspectRatioIcon />, "AspectRatio"],
  Avatar: [<AvatarIcon />, "Avatar"],
  Backpack: [<BackpackIcon />, "Backpack"],
  Badge: [<BadgeIcon />, "Badge"],
  BarChart: [<BarChartIcon />, "BarChart"],
  Bell: [<BellIcon />, "Bell"],
  BlendingMode: [<BlendingModeIcon />, "BlendingMode"],
  BookmarkFilled: [<BookmarkFilledIcon />, "BookmarkFilled"],
  Bookmark: [<BookmarkIcon />, "Bookmark"],
  BorderAll: [<BorderAllIcon />, "BorderAll"],
  BorderBottom: [<BorderBottomIcon />, "BorderBottom"],
  BorderDashed: [<BorderDashedIcon />, "BorderDashed"],
  BorderDotted: [<BorderDottedIcon />, "BorderDotted"],
  BorderLeft: [<BorderLeftIcon />, "BorderLeft"],
  BorderNone: [<BorderNoneIcon />, "BorderNone"],
  BorderRight: [<BorderRightIcon />, "BorderRight"],
  BorderSolid: [<BorderSolidIcon />, "BorderSolid"],
  BorderSplit: [<BorderSplitIcon />, "BorderSplit"],
  BorderStyle: [<BorderStyleIcon />, "BorderStyle"],
  BorderTop: [<BorderTopIcon />, "BorderTop"],
  BorderWidth: [<BorderWidthIcon />, "BorderWidth"],
  Box: [<BoxIcon />, "Box"],
  BoxModel: [<BoxModelIcon />, "BoxModel"],
  Button: [<ButtonIcon />, "Button"],
  Calendar: [<CalendarIcon />, "Calendar"],
  Camera: [<CameraIcon />, "Camera"],
  CardStack: [<CardStackIcon />, "CardStack"],
  CardStackMinus: [<CardStackMinusIcon />, "CardStackMinus"],
  CardStackPlus: [<CardStackPlusIcon />, "CardStackPlus"],
  CaretDown: [<CaretDownIcon />, "CaretDown"],
  CaretLeft: [<CaretLeftIcon />, "CaretLeft"],
  CaretRight: [<CaretRightIcon />, "CaretRight"],
  CaretSort: [<CaretSortIcon />, "CaretSort"],
  CaretUp: [<CaretUpIcon />, "CaretUp"],
  ChatBubble: [<ChatBubbleIcon />, "ChatBubble"],
  CheckCircled: [<CheckCircledIcon />, "CheckCircled"],
  Check: [<CheckIcon />, "Check"],
  Checkbox: [<CheckboxIcon />, "Checkbox"],
  ChevronDown: [<ChevronDownIcon />, "ChevronDown"],
  ChevronLeft: [<ChevronLeftIcon />, "ChevronLeft"],
  ChevronRight: [<ChevronRightIcon />, "ChevronRight"],
  ChevronUp: [<ChevronUpIcon />, "ChevronUp"],
  CircleBackslash: [<CircleBackslashIcon />, "CircleBackslash"],
  Circle: [<CircleIcon />, "Circle"],
  ClipboardCopy: [<ClipboardCopyIcon />, "ClipboardCopy"],
  Clipboard: [<ClipboardIcon />, "Clipboard"],
  Clock: [<ClockIcon />, "Clock"],
  Code: [<CodeIcon />, "Code"],
  CodeSandboxLogo: [<CodeSandboxLogoIcon />, "CodeSandboxLogo"],
  ColorWheel: [<ColorWheelIcon />, "ColorWheel"],
  ColumnSpacing: [<ColumnSpacingIcon />, "ColumnSpacing"],
  Columns: [<ColumnsIcon />, "Columns"],
  Commit: [<CommitIcon />, "Commit"],
  Component1: [<Component1Icon />, "Component1"],
  Component2: [<Component2Icon />, "Component2"],
  ComponentBoolean: [<ComponentBooleanIcon />, "ComponentBoolean"],
  ComponentInstance: [<ComponentInstanceIcon />, "ComponentInstance"],
  ComponentNone: [<ComponentNoneIcon />, "ComponentNone"],
  ComponentPlaceholder: [<ComponentPlaceholderIcon />, "ComponentPlaceholder"],
  Container: [<ContainerIcon />, "Container"],
  Cookie: [<CookieIcon />, "Cookie"],
  Copy: [<CopyIcon />, "Copy"],
  CornerBottomLeft: [<CornerBottomLeftIcon />, "CornerBottomLeft"],
  CornerBottomRight: [<CornerBottomRightIcon />, "CornerBottomRight"],
  CornerTopLeft: [<CornerTopLeftIcon />, "CornerTopLeft"],
  CornerTopRight: [<CornerTopRightIcon />, "CornerTopRight"],
  Corners: [<CornersIcon />, "Corners"],
  CountdownTimer: [<CountdownTimerIcon />, "CountdownTimer"],
  CounterClockwiseClock: [
    <CounterClockwiseClockIcon />,
    "CounterClockwiseClock",
  ],
  Crop: [<CropIcon />, "Crop"],
  Cross1: [<Cross1Icon />, "Cross1"],
  Cross2: [<Cross2Icon />, "Cross2"],
  CrossCircled: [<CrossCircledIcon />, "CrossCircled"],
  Crosshair1: [<Crosshair1Icon />, "Crosshair1"],
  Crosshair2: [<Crosshair2Icon />, "Crosshair2"],
  CrumpledPaper: [<CrumpledPaperIcon />, "CrumpledPaper"],
  Cube: [<CubeIcon />, "Cube"],
  CursorArrow: [<CursorArrowIcon />, "CursorArrow"],
  CursorText: [<CursorTextIcon />, "CursorText"],
  Dash: [<DashIcon />, "Dash"],
  Dashboard: [<DashboardIcon />, "Dashboard"],
  Desktop: [<DesktopIcon />, "Desktop"],
  Dimensions: [<DimensionsIcon />, "Dimensions"],
  Disc: [<DiscIcon />, "Disc"],
  DiscordLogo: [<DiscordLogoIcon />, "DiscordLogo"],
  DividerHorizontal: [<DividerHorizontalIcon />, "DividerHorizontal"],
  DividerVertical: [<DividerVerticalIcon />, "DividerVertical"],
  DotFilled: [<DotFilledIcon />, "DotFilled"],
  Dot: [<DotIcon />, "Dot"],
  DotsHorizontal: [<DotsHorizontalIcon />, "DotsHorizontal"],
  DotsVertical: [<DotsVerticalIcon />, "DotsVertical"],
  DoubleArrowDown: [<DoubleArrowDownIcon />, "DoubleArrowDown"],
  DoubleArrowLeft: [<DoubleArrowLeftIcon />, "DoubleArrowLeft"],
  DoubleArrowRight: [<DoubleArrowRightIcon />, "DoubleArrowRight"],
  DoubleArrowUp: [<DoubleArrowUpIcon />, "DoubleArrowUp"],
  Download: [<DownloadIcon />, "Download"],
  DragHandleDots1: [<DragHandleDots1Icon />, "DragHandleDots1"],
  DragHandleDots2: [<DragHandleDots2Icon />, "DragHandleDots2"],
  DragHandleHorizontal: [<DragHandleHorizontalIcon />, "DragHandleHorizontal"],
  DragHandleVertical: [<DragHandleVerticalIcon />, "DragHandleVertical"],
  DrawingPinFilled: [<DrawingPinFilledIcon />, "DrawingPinFilled"],
  DrawingPin: [<DrawingPinIcon />, "DrawingPin"],
  DropdownMenu: [<DropdownMenuIcon />, "DropdownMenu"],
  EnterFullScreen: [<EnterFullScreenIcon />, "EnterFullScreen"],
  Enter: [<EnterIcon />, "Enter"],
  EnvelopeClosed: [<EnvelopeClosedIcon />, "EnvelopeClosed"],
  EnvelopeOpen: [<EnvelopeOpenIcon />, "EnvelopeOpen"],
  Eraser: [<EraserIcon />, "Eraser"],
  ExclamationTriangle: [<ExclamationTriangleIcon />, "ExclamationTriangle"],
  ExitFullScreen: [<ExitFullScreenIcon />, "ExitFullScreen"],
  Exit: [<ExitIcon />, "Exit"],
  ExternalLink: [<ExternalLinkIcon />, "ExternalLink"],
  EyeClosed: [<EyeClosedIcon />, "EyeClosed"],
  EyeNone: [<EyeNoneIcon />, "EyeNone"],
  EyeOpen: [<EyeOpenIcon />, "EyeOpen"],
  Face: [<FaceIcon />, "Face"],
  FigmaLogo: [<FigmaLogoIcon />, "FigmaLogo"],
  File: [<FileIcon />, "File"],
  FileMinus: [<FileMinusIcon />, "FileMinus"],
  FilePlus: [<FilePlusIcon />, "FilePlus"],
  FileText: [<FileTextIcon />, "FileText"],
  FontBold: [<FontBoldIcon />, "FontBold"],
  FontFamily: [<FontFamilyIcon />, "FontFamily"],
  FontItalic: [<FontItalicIcon />, "FontItalic"],
  FontRoman: [<FontRomanIcon />, "FontRoman"],
  FontSize: [<FontSizeIcon />, "FontSize"],
  FontStyle: [<FontStyleIcon />, "FontStyle"],
  Frame: [<FrameIcon />, "Frame"],
  FramerLogo: [<FramerLogoIcon />, "FramerLogo"],
  Gear: [<GearIcon />, "Gear"],
  GitHubLogo: [<GitHubLogoIcon />, "GitHubLogo"],
  Globe: [<GlobeIcon />, "Globe"],
  Grid: [<GridIcon />, "Grid"],
  Group: [<GroupIcon />, "Group"],
  Half1: [<Half1Icon />, "Half1"],
  Half2: [<Half2Icon />, "Half2"],
  HamburgerMenu: [<HamburgerMenuIcon />, "HamburgerMenu"],
  Hand: [<HandIcon />, "Hand"],
  Heading: [<HeadingIcon />, "Heading"],
  HeartFilled: [<HeartFilledIcon />, "HeartFilled"],
  Heart: [<HeartIcon />, "Heart"],
  Height: [<HeightIcon />, "Height"],
  HobbyKnife: [<HobbyKnifeIcon />, "HobbyKnife"],
  Home: [<HomeIcon />, "Home"],
  IconJarLogo: [<IconJarLogoIcon />, "IconJarLogo"],
  IdCard: [<IdCardIcon />, "IdCard"],
  Image: [<ImageIcon />, "Image"],
  InfoCircled: [<InfoCircledIcon />, "InfoCircled"],
  Input: [<InputIcon />, "Input"],
  InstagramLogo: [<InstagramLogoIcon />, "InstagramLogo"],
  Keyboard: [<KeyboardIcon />, "Keyboard"],
  LapTimer: [<LapTimerIcon />, "LapTimer"],
  Laptop: [<LaptopIcon />, "Laptop"],
  Layers: [<LayersIcon />, "Layers"],
  Layout: [<LayoutIcon />, "Layout"],
  LetterCaseCapitalize: [<LetterCaseCapitalizeIcon />, "LetterCaseCapitalize"],
  LetterCaseLowercase: [<LetterCaseLowercaseIcon />, "LetterCaseLowercase"],
  LetterCaseToggle: [<LetterCaseToggleIcon />, "LetterCaseToggle"],
  LetterCaseUppercase: [<LetterCaseUppercaseIcon />, "LetterCaseUppercase"],
  LetterSpacing: [<LetterSpacingIcon />, "LetterSpacing"],
  LightningBolt: [<LightningBoltIcon />, "LightningBolt"],
  LineHeight: [<LineHeightIcon />, "LineHeight"],
  Link1: [<Link1Icon />, "Link1"],
  Link2: [<Link2Icon />, "Link2"],
  LinkBreak1: [<LinkBreak1Icon />, "LinkBreak1"],
  LinkBreak2: [<LinkBreak2Icon />, "LinkBreak2"],
  LinkNone1: [<LinkNone1Icon />, "LinkNone1"],
  LinkNone2: [<LinkNone2Icon />, "LinkNone2"],
  LinkedInLogo: [<LinkedInLogoIcon />, "LinkedInLogo"],
  ListBullet: [<ListBulletIcon />, "ListBullet"],
  LockClosed: [<LockClosedIcon />, "LockClosed"],
  LockOpen1: [<LockOpen1Icon />, "LockOpen1"],
  LockOpen2: [<LockOpen2Icon />, "LockOpen2"],
  Loop: [<LoopIcon />, "Loop"],
  MagicWand: [<MagicWandIcon />, "MagicWand"],
  MagnifyingGlass: [<MagnifyingGlassIcon />, "MagnifyingGlass"],
  Margin: [<MarginIcon />, "Margin"],
  MaskOff: [<MaskOffIcon />, "MaskOff"],
  MaskOn: [<MaskOnIcon />, "MaskOn"],
  MinusCircled: [<MinusCircledIcon />, "MinusCircled"],
  Minus: [<MinusIcon />, "Minus"],
  Mix: [<MixIcon />, "Mix"],
  MixerHorizontal: [<MixerHorizontalIcon />, "MixerHorizontal"],
  MixerVertical: [<MixerVerticalIcon />, "MixerVertical"],
  Mobile: [<MobileIcon />, "Mobile"],
  ModulzLogo: [<ModulzLogoIcon />, "ModulzLogo"],
  Moon: [<MoonIcon />, "Moon"],
  Move: [<MoveIcon />, "Move"],
  NotionLogo: [<NotionLogoIcon />, "NotionLogo"],
  Opacity: [<OpacityIcon />, "Opacity"],
  OpenInNewWindow: [<OpenInNewWindowIcon />, "OpenInNewWindow"],
  Overline: [<OverlineIcon />, "Overline"],
  Padding: [<PaddingIcon />, "Padding"],
  PaperPlane: [<PaperPlaneIcon />, "PaperPlane"],
  Pause: [<PauseIcon />, "Pause"],
  Pencil1: [<Pencil1Icon />, "Pencil1"],
  Pencil2: [<Pencil2Icon />, "Pencil2"],
  Person: [<PersonIcon />, "Person"],
  PieChart: [<PieChartIcon />, "PieChart"],
  Pilcrow: [<PilcrowIcon />, "Pilcrow"],
  PinBottom: [<PinBottomIcon />, "PinBottom"],
  PinLeft: [<PinLeftIcon />, "PinLeft"],
  PinRight: [<PinRightIcon />, "PinRight"],
  PinTop: [<PinTopIcon />, "PinTop"],
  Play: [<PlayIcon />, "Play"],
  PlusCircled: [<PlusCircledIcon />, "PlusCircled"],
  Plus: [<PlusIcon />, "Plus"],
  QuestionMarkCircled: [<QuestionMarkCircledIcon />, "QuestionMarkCircled"],
  QuestionMark: [<QuestionMarkIcon />, "QuestionMark"],
  Quote: [<QuoteIcon />, "Quote"],
  Radiobutton: [<RadiobuttonIcon />, "Radiobutton"],
  Reader: [<ReaderIcon />, "Reader"],
  Reload: [<ReloadIcon />, "Reload"],
  Reset: [<ResetIcon />, "Reset"],
  Resume: [<ResumeIcon />, "Resume"],
  Rocket: [<RocketIcon />, "Rocket"],
  RotateCounterClockwise: [
    <RotateCounterClockwiseIcon />,
    "RotateCounterClockwise",
  ],
  RowSpacing: [<RowSpacingIcon />, "RowSpacing"],
  Rows: [<RowsIcon />, "Rows"],
  RulerHorizontal: [<RulerHorizontalIcon />, "RulerHorizontal"],
  RulerSquare: [<RulerSquareIcon />, "RulerSquare"],
  Scissors: [<ScissorsIcon />, "Scissors"],
  Section: [<SectionIcon />, "Section"],
  SewingPinFilled: [<SewingPinFilledIcon />, "SewingPinFilled"],
  SewingPin: [<SewingPinIcon />, "SewingPin"],
  Shadow: [<ShadowIcon />, "Shadow"],
  ShadowInner: [<ShadowInnerIcon />, "ShadowInner"],
  ShadowNone: [<ShadowNoneIcon />, "ShadowNone"],
  ShadowOuter: [<ShadowOuterIcon />, "ShadowOuter"],
  Share1: [<Share1Icon />, "Share1"],
  Share2: [<Share2Icon />, "Share2"],
  Shuffle: [<ShuffleIcon />, "Shuffle"],
  Size: [<SizeIcon />, "Size"],
  SketchLogo: [<SketchLogoIcon />, "SketchLogo"],
  Slash: [<SlashIcon />, "Slash"],
  Slider: [<SliderIcon />, "Slider"],
  SpaceBetweenHorizontally: [
    <SpaceBetweenHorizontallyIcon />,
    "SpaceBetweenHorizontally",
  ],
  SpaceBetweenVertically: [
    <SpaceBetweenVerticallyIcon />,
    "SpaceBetweenVertically",
  ],
  SpaceEvenlyHorizontally: [
    <SpaceEvenlyHorizontallyIcon />,
    "SpaceEvenlyHorizontally",
  ],
  SpaceEvenlyVertically: [
    <SpaceEvenlyVerticallyIcon />,
    "SpaceEvenlyVertically",
  ],
  SpeakerLoud: [<SpeakerLoudIcon />, "SpeakerLoud"],
  SpeakerModerate: [<SpeakerModerateIcon />, "SpeakerModerate"],
  SpeakerOff: [<SpeakerOffIcon />, "SpeakerOff"],
  SpeakerQuiet: [<SpeakerQuietIcon />, "SpeakerQuiet"],
  Square: [<SquareIcon />, "Square"],
  Stack: [<StackIcon />, "Stack"],
  StarFilled: [<StarFilledIcon />, "StarFilled"],
  Star: [<StarIcon />, "Star"],
  StitchesLogo: [<StitchesLogoIcon />, "StitchesLogo"],
  Stop: [<StopIcon />, "Stop"],
  Stopwatch: [<StopwatchIcon />, "Stopwatch"],
  StretchHorizontally: [<StretchHorizontallyIcon />, "StretchHorizontally"],
  StretchVertically: [<StretchVerticallyIcon />, "StretchVertically"],
  Strikethrough: [<StrikethroughIcon />, "Strikethrough"],
  Sun: [<SunIcon />, "Sun"],
  Switch: [<SwitchIcon />, "Switch"],
  Symbol: [<SymbolIcon />, "Symbol"],
  Table: [<TableIcon />, "Table"],
  Target: [<TargetIcon />, "Target"],
  TextAlignBottom: [<TextAlignBottomIcon />, "TextAlignBottom"],
  TextAlignCenter: [<TextAlignCenterIcon />, "TextAlignCenter"],
  TextAlignJustify: [<TextAlignJustifyIcon />, "TextAlignJustify"],
  TextAlignLeft: [<TextAlignLeftIcon />, "TextAlignLeft"],
  TextAlignMiddle: [<TextAlignMiddleIcon />, "TextAlignMiddle"],
  TextAlignRight: [<TextAlignRightIcon />, "TextAlignRight"],
  TextAlignTop: [<TextAlignTopIcon />, "TextAlignTop"],
  Text: [<TextIcon />, "Text"],
  TextNone: [<TextNoneIcon />, "TextNone"],
  ThickArrowDown: [<ThickArrowDownIcon />, "ThickArrowDown"],
  ThickArrowLeft: [<ThickArrowLeftIcon />, "ThickArrowLeft"],
  ThickArrowRight: [<ThickArrowRightIcon />, "ThickArrowRight"],
  ThickArrowUp: [<ThickArrowUpIcon />, "ThickArrowUp"],
  Timer: [<TimerIcon />, "Timer"],
  Tokens: [<TokensIcon />, "Tokens"],
  TrackNext: [<TrackNextIcon />, "TrackNext"],
  TrackPrevious: [<TrackPreviousIcon />, "TrackPrevious"],
  Transform: [<TransformIcon />, "Transform"],
  TransparencyGrid: [<TransparencyGridIcon />, "TransparencyGrid"],
  Trash: [<TrashIcon />, "Trash"],
  TriangleDown: [<TriangleDownIcon />, "TriangleDown"],
  TriangleLeft: [<TriangleLeftIcon />, "TriangleLeft"],
  TriangleRight: [<TriangleRightIcon />, "TriangleRight"],
  TriangleUp: [<TriangleUpIcon />, "TriangleUp"],
  TwitterLogo: [<TwitterLogoIcon />, "TwitterLogo"],
  Underline: [<UnderlineIcon />, "Underline"],
  Update: [<UpdateIcon />, "Update"],
  Upload: [<UploadIcon />, "Upload"],
  Value: [<ValueIcon />, "Value"],
  ValueNone: [<ValueNoneIcon />, "ValueNone"],
  VercelLogo: [<VercelLogoIcon />, "VercelLogo"],
  Video: [<VideoIcon />, "Video"],
  ViewGrid: [<ViewGridIcon />, "ViewGrid"],
  ViewHorizontal: [<ViewHorizontalIcon />, "ViewHorizontal"],
  ViewNone: [<ViewNoneIcon />, "ViewNone"],
  ViewVertical: [<ViewVerticalIcon />, "ViewVertical"],
  Width: [<WidthIcon />, "Width"],
  ZoomIn: [<ZoomInIcon />, "ZoomIn"],
  ZoomOut: [<ZoomOutIcon />, "ZoomOut"],
};

export type RadixIcon = keyof typeof RADIX_ICONS;
